package me.iamhardyha.bugbuddy.model.enums;

public enum XpEventType {
    QUESTION_CREATED,
    ANSWER_CREATED,
    ANSWER_HELPFUL_RECEIVED,
    ANSWER_ACCEPTED,
    CHAT_FEEDBACK_POSITIVE,
    CHAT_FEEDBACK_NEGATIVE,
    FEED_CREATED,
    FEED_LIKED_RECEIVED,
    ADMIN_ADJUST,
    OTHER
}
